# workloads/app-hello.yml
#
# --- VERSÃO 2 (Raw Manifests) ---
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  
  # --- CORREÇÃO ---
  # A fonte agora é o nosso próprio Git, apontando
  # para o diretório de manifestos que criamos.
  source:
    repoURL: https://github.com/rodrigo-zvd/k3s-proxmox-homelab.git
    targetRevision: HEAD
    path: workloads/nginx-simple # <--- APONTA PARA OS NOVOS ARQUIVOS
    
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true